-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 17:41:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema r4_php_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `r4_php_db` ;

-- -----------------------------------------------------
-- Schema r4_php_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `r4_php_db` DEFAULT CHARACTER SET utf8 ;
USE `r4_php_db` ;

-- -----------------------------------------------------
-- Table `r4_php_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r4_php_db`.`users` ;

CREATE TABLE IF NOT EXISTS `r4_php_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(75) NOT NULL,
  `reset_senha` TINYINT NULL,
  `remember_token` VARCHAR(100) NULL,
  `avatar` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r4_php_db`.`throttles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r4_php_db`.`throttles` ;

CREATE TABLE IF NOT EXISTS `r4_php_db`.`throttles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NULL,
  `is_default_password` TINYINT(4) NOT NULL,
  `last_access_at` TIMESTAMP NULL,
  `attempts` TINYINT(4) NULL,
  `suspended` TINYINT NULL,
  `last_attempt_at` TIMESTAMP NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_throttles_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_throttles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `r4_php_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r4_php_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r4_php_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `r4_php_db`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r4_php_db`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r4_php_db`.`users_roles` ;

CREATE TABLE IF NOT EXISTS `r4_php_db`.`users_roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_roles_roles1_idx` (`role_id` ASC),
  INDEX `fk_users_has_roles_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `r4_php_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `r4_php_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r4_php_db`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r4_php_db`.`comments` ;

CREATE TABLE IF NOT EXISTS `r4_php_db`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(400) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `r4_php_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r4_php_db`.`comments_updates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r4_php_db`.`comments_updates` ;

CREATE TABLE IF NOT EXISTS `r4_php_db`.`comments_updates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_updates_comment_idx` (`comment_id` ASC),
  CONSTRAINT `fk_comments_updates_comments`
    FOREIGN KEY (`comment_id`)
    REFERENCES `r4_php_db`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `r4_php_db`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r4_php_db`.`loggers` ;

CREATE TABLE IF NOT EXISTS `r4_php_db`.`loggers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NULL,
  `message` VARCHAR(200) NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loggers_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_loggers_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `r4_php_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -------------------------

INSERT INTO `roles` VALUES
(1, 'ROOT', 'Desenvolvedor'),
(2, 'ADMIN', 'Administrador do Sistema'),
(3, 'USUARIO', 'Usuário Comum');

INSERT INTO `users` VALUES
(1, 'Administrador', 'ADMIN', 'mayradbueno@gmail.com', '$2y$10$hravkHv4Whx6oXsw1jMwsOAovVvQ29vlTwVlLox1lgq9ZZUFOG6MO', 0,
'$2y$10$X/ri8NeCdc3oc2swndWwQ.uZSjDZFVMmaIS1/zQAMNg16cIaEbWJu', null, now(), null, null);

INSERT INTO `throttles` VALUES
(1, NULL, 0, NULL, 0, 0, NULL, 1);

INSERT INTO `users_roles` (`id`, `user_id`, `role_id`) VALUES
(1,1,1),(2,1,2),(3,1,3);
